[package]
name = "guest-common"
version = "0.1.0"
edition.workspace = true

[dependencies]
chrono = { workspace = true, features = ["std", "clock"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[lints]
workspace = true
