[package]
name = "vm-download"
version = "0.1.0"
edition = "2024"

[dependencies]
vm-common = { path = "../vm-common" }
ureq = { version = "3", features = ["platform-verifier"] }
flate2 = "1"
tar = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints]
workspace = true
